version: '2.1'

services:
   app:
      restart: always
      build:
        context: ./miontest
      volumes:
        - ./miontest/src:/miontest/src
      ports: 
        - 3000:3000 
   postgres:
      image: postgres
      restart: always
      environment: 
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root
      ports: 
        - "5432:5432"
   pgadmin-compose:
      image: dpage/pgadmin4
      environment: 
        PGADMIN_DEFAULT_EMAIL: "khatanzorigb@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "hatnaa20!@#"
      ports: 
        - "16543:80"
      depends_on: 
        - postgres

   back:
      restart: always
      build: 
        context: ./miontestservice
      ports: 
        - 8000:8000
