FROM node:14 

MAINTAINER 弥海砂 <https://github.com/amane312>

WORKDIR /back 

ENV PATH /back/node_modules/.bin:$PATH

COPY package.json ./

# COPY package-lock.json ./


#   Run compilation and instalation commands

# RUN  npm ci  
RUN  npm install 

#  RUN npm install react-scripts@4.0.2 -g

COPY . .


# RUN npm run build

# fire pyun pyun pyunnnnnnn
CMD ["nodemon", "start.js"]